ALTER TABLE CHIEN DROP CONSTRAINT FK_CHIEN_PROPRIO_ID
ALTER TABLE CHIEN DROP CONSTRAINT FK_CHIEN_CHENIL_ID
ALTER TABLE CHIEN_PATHOLOGIE DROP CONSTRAINT FK_CHIEN_PATHOLOGIE_CHIEN_ID
ALTER TABLE CHIEN_PATHOLOGIE DROP CONSTRAINT FK_CHIEN_PATHOLOGIE_PATHOLOGIE_NAME
DROP TABLE PERSONNE CASCADE
DROP TABLE CHIEN CASCADE
DROP TABLE CHENIL CASCADE
DROP TABLE PATHOLOGIE CASCADE
DROP TABLE CHIEN_PATHOLOGIE CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
